# Auto-generated by the CustomAssets editor's LegacyMigrator.
# Consolidates the per-file dependencies(...) calls that used to
# live in individual Definitions/*.py files into explicit imports
# here — load order follows the line order below.
import liquified_coal
import coal_liquification
